version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    revive:
      rules:
        - name: comment-spacings

  exclusions:
    generated: lax
    rules:
      - path: _test.go
        linters:
          - goconst # tests often avoid constants for readability
          - dupl # duplication is usually intended in tests
          - lll # long lines usually acceptable in tests

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
