---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: controller
  labels:
    app: container-object-storage-interface-controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: container-object-storage-interface-controller
  template:
    metadata:
      labels:
        app: container-object-storage-interface-controller
    spec:
      serviceAccountName: controller-sa
      containers:
        - name: objectstorage-controller
          image: gcr.io/k8s-staging-sig-storage/objectstorage-controller:v20250905-controllerv0.2.0-rc1-100-gd904c62
          args:
            - "--v=5"
